/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FeedbackTokenRouteImport } from './routes/feedback.$token'
import { Route as AppUsersRouteImport } from './routes/_app.users'
import { Route as AppLearningRouteImport } from './routes/_app.learning'
import { Route as AppInspirationRouteImport } from './routes/_app.inspiration'
import { Route as AppFeedbackRouteImport } from './routes/_app.feedback'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppDailyLogRouteImport } from './routes/_app.daily-log'
import { Route as AppClientsRouteImport } from './routes/_app.clients'
import { Route as AppCalculatorRouteImport } from './routes/_app.calculator'
import { Route as AppClientsIdRouteImport } from './routes/_app.clients.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackTokenRoute = FeedbackTokenRouteImport.update({
  id: '/feedback/$token',
  path: '/feedback/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppLearningRoute = AppLearningRouteImport.update({
  id: '/learning',
  path: '/learning',
  getParentRoute: () => AppRoute,
} as any)
const AppInspirationRoute = AppInspirationRouteImport.update({
  id: '/inspiration',
  path: '/inspiration',
  getParentRoute: () => AppRoute,
} as any)
const AppFeedbackRoute = AppFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppDailyLogRoute = AppDailyLogRouteImport.update({
  id: '/daily-log',
  path: '/daily-log',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsRoute = AppClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AppRoute,
} as any)
const AppCalculatorRoute = AppCalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsIdRoute = AppClientsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppClientsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/calculator': typeof AppCalculatorRoute
  '/clients': typeof AppClientsRouteWithChildren
  '/daily-log': typeof AppDailyLogRoute
  '/dashboard': typeof AppDashboardRoute
  '/feedback': typeof AppFeedbackRoute
  '/inspiration': typeof AppInspirationRoute
  '/learning': typeof AppLearningRoute
  '/users': typeof AppUsersRoute
  '/feedback/$token': typeof FeedbackTokenRoute
  '/clients/$id': typeof AppClientsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/calculator': typeof AppCalculatorRoute
  '/clients': typeof AppClientsRouteWithChildren
  '/daily-log': typeof AppDailyLogRoute
  '/dashboard': typeof AppDashboardRoute
  '/feedback': typeof AppFeedbackRoute
  '/inspiration': typeof AppInspirationRoute
  '/learning': typeof AppLearningRoute
  '/users': typeof AppUsersRoute
  '/feedback/$token': typeof FeedbackTokenRoute
  '/clients/$id': typeof AppClientsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/calculator': typeof AppCalculatorRoute
  '/_app/clients': typeof AppClientsRouteWithChildren
  '/_app/daily-log': typeof AppDailyLogRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/feedback': typeof AppFeedbackRoute
  '/_app/inspiration': typeof AppInspirationRoute
  '/_app/learning': typeof AppLearningRoute
  '/_app/users': typeof AppUsersRoute
  '/feedback/$token': typeof FeedbackTokenRoute
  '/_app/clients/$id': typeof AppClientsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/calculator'
    | '/clients'
    | '/daily-log'
    | '/dashboard'
    | '/feedback'
    | '/inspiration'
    | '/learning'
    | '/users'
    | '/feedback/$token'
    | '/clients/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/calculator'
    | '/clients'
    | '/daily-log'
    | '/dashboard'
    | '/feedback'
    | '/inspiration'
    | '/learning'
    | '/users'
    | '/feedback/$token'
    | '/clients/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/calculator'
    | '/_app/clients'
    | '/_app/daily-log'
    | '/_app/dashboard'
    | '/_app/feedback'
    | '/_app/inspiration'
    | '/_app/learning'
    | '/_app/users'
    | '/feedback/$token'
    | '/_app/clients/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  FeedbackTokenRoute: typeof FeedbackTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback/$token': {
      id: '/feedback/$token'
      path: '/feedback/$token'
      fullPath: '/feedback/$token'
      preLoaderRoute: typeof FeedbackTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/learning': {
      id: '/_app/learning'
      path: '/learning'
      fullPath: '/learning'
      preLoaderRoute: typeof AppLearningRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inspiration': {
      id: '/_app/inspiration'
      path: '/inspiration'
      fullPath: '/inspiration'
      preLoaderRoute: typeof AppInspirationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/feedback': {
      id: '/_app/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof AppFeedbackRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/daily-log': {
      id: '/_app/daily-log'
      path: '/daily-log'
      fullPath: '/daily-log'
      preLoaderRoute: typeof AppDailyLogRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clients': {
      id: '/_app/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AppClientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calculator': {
      id: '/_app/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof AppCalculatorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clients/$id': {
      id: '/_app/clients/$id'
      path: '/$id'
      fullPath: '/clients/$id'
      preLoaderRoute: typeof AppClientsIdRouteImport
      parentRoute: typeof AppClientsRoute
    }
  }
}

interface AppClientsRouteChildren {
  AppClientsIdRoute: typeof AppClientsIdRoute
}

const AppClientsRouteChildren: AppClientsRouteChildren = {
  AppClientsIdRoute: AppClientsIdRoute,
}

const AppClientsRouteWithChildren = AppClientsRoute._addFileChildren(
  AppClientsRouteChildren,
)

interface AppRouteChildren {
  AppCalculatorRoute: typeof AppCalculatorRoute
  AppClientsRoute: typeof AppClientsRouteWithChildren
  AppDailyLogRoute: typeof AppDailyLogRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppFeedbackRoute: typeof AppFeedbackRoute
  AppInspirationRoute: typeof AppInspirationRoute
  AppLearningRoute: typeof AppLearningRoute
  AppUsersRoute: typeof AppUsersRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCalculatorRoute: AppCalculatorRoute,
  AppClientsRoute: AppClientsRouteWithChildren,
  AppDailyLogRoute: AppDailyLogRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppFeedbackRoute: AppFeedbackRoute,
  AppInspirationRoute: AppInspirationRoute,
  AppLearningRoute: AppLearningRoute,
  AppUsersRoute: AppUsersRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  FeedbackTokenRoute: FeedbackTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
